[project.scripts]
# Aqui definimos el comando corto.
# Importante: Quitamos el prefijo "src." porque definiremos "src" como la raiz.
app = "main:main"

[tool.uv]
package = true

# Esta seccion es crucial para que Python vea el contenido de src como el nivel raiz 
[tool.setuptools.package-dir]
"" = "src"